"""initial database tables

Revision ID: 511cf9fee51e
Revises: 
Create Date: 2026-04-29 16:18:52.699648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511cf9fee51e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='MODERATE', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('reporter_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_reports_id'), 'community_reports', ['id'], unique=False)
    op.create_index(op.f('ix_community_reports_location_id'), 'community_reports', ['location_id'], unique=False)
    op.create_index(op.f('ix_community_reports_status'), 'community_reports', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('rainfall_mm_hr', sa.Float(), nullable=False),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=False),
    sa.Column('tilt_deg', sa.Float(), nullable=False),
    sa.Column('vegetation_change_pct', sa.Float(), nullable=False),
    sa.Column('satellite_risk_index', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('alert_generated', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_location_id'), 'predictions', ['location_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_location_id'), 'alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_alerts_prediction_id'), 'alerts', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_prediction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_location_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_location_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_community_reports_status'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_location_id'), table_name='community_reports')
    op.drop_index(op.f('ix_community_reports_id'), table_name='community_reports')
    op.drop_table('community_reports')
    # ### end Alembic commands ###
